name: F1 Live Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Script ausführen
        run: python scraper.py

      - name: Commit output.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output.json
          git commit -m "update" || echo "no changes"
          git push

- name: Dependencies
  run: pip install -r requirements.txt
